#ifndef ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___
#define ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___

class ___FILEBASENAMEASIDENTIFIER___
{
public:
    ___FILEBASENAMEASIDENTIFIER___();
    virtual ~___FILEBASENAMEASIDENTIFIER___();
    
private:
    ___FILEBASENAMEASIDENTIFIER___(const ___FILEBASENAMEASIDENTIFIER___ &other);
    ___FILEBASENAMEASIDENTIFIER___& operator=(const ___FILEBASENAMEASIDENTIFIER___ &other);
};

#endif